import fs from "node:fs";
import type { Secrets } from "./types.js";
import { envFilePath } from "./paths.js";

const DEFAULT_SECRETS: Secrets = {
  integrationToken: "",
  clientId: "",
  clientSecret: "",
  authUrl: "https://auth.regos.uz",
  apiBase: "https://integration.regos.uz/gateway/out",
};

export function parseEnvFile(filePath: string): Record<string, string> {
  if (!fs.existsSync(filePath)) return {};
  const result: Record<string, string> = {};
  for (const rawLine of fs.readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

export function loadSecrets(): Secrets {
  const env = parseEnvFile(envFilePath());
  return {
    integrationToken: env.REGOS_INTEGRATION_TOKEN ?? DEFAULT_SECRETS.integrationToken,
    clientId: env.REGOS_CLIENT_ID ?? DEFAULT_SECRETS.clientId,
    clientSecret: env.REGOS_CLIENT_SECRET ?? DEFAULT_SECRETS.clientSecret,
    authUrl: env.REGOS_AUTH_URL || DEFAULT_SECRETS.authUrl,
    apiBase: env.REGOS_API_BASE || DEFAULT_SECRETS.apiBase,
  };
}

function envValue(value: string): string {
  if (/[\s#"']/.test(value)) {
    return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
  }
  return value;
}

export function saveSecrets(secrets: Secrets): void {
  const content = [
    "# Generated by Regos MXIK Updater",
    `REGOS_INTEGRATION_TOKEN=${envValue(secrets.integrationToken.trim())}`,
    "",
    "# Required only for catalog integrations that use OAuth.",
    "# Leave empty when using a local integration token.",
    `REGOS_CLIENT_ID=${envValue(secrets.clientId.trim())}`,
    `REGOS_CLIENT_SECRET=${envValue(secrets.clientSecret.trim())}`,
    "",
    `REGOS_AUTH_URL=${envValue((secrets.authUrl.trim() || DEFAULT_SECRETS.authUrl).replace(/\/+$/, ""))}`,
    `REGOS_API_BASE=${envValue((secrets.apiBase.trim() || DEFAULT_SECRETS.apiBase).replace(/\/+$/, ""))}`,
    "",
  ].join("\n");
  fs.writeFileSync(envFilePath(), content, "utf8");
}

export { DEFAULT_SECRETS, envFilePath };
